name: Release

on:
  push:
    branches:
      - master
      - main
      
  workflow_dispatch:
    inputs:
      bump:
        description: bump rule (major|minor|patch|premajor|preminor|prepatch|prerelease)
        default: prerelease
        required: false
        
      version:
        description: manual version
        default: ''
        required: false
        
      grpc_version:
        description: manual grpc version
        default: ''
        required: false
        
      release:
        description: release type (local|global)
        default: local
        required: false
        
# Secrets:
#   pypi_token - pypi API token
      
jobs:
  Release:
    runs-on: ubuntu-latest
    env:
      BUMP: ${{ github.event.inputs.bump }} # default values for push-triggered run
      RELEASE: local
      VERSION: ${{ github.event.inputs.version }}
      GRPC_VERSION: ${{ github.event.inputs.grpc_version }}
    steps:
      - name: Validate inputs  #TODO create an action for this
        if: github.event_name == 'workflow_dispatch'
        run: |
          case ${{ github.event.inputs.bump }} in
            major)
              ;;
            premajor)
              ;;
            minor)
              ;;
            preminor)
              ;;
            patch)
              ;;
            prepatch)
              ;;
            prerelease)
              ;;
            *)
              echo "invalid bump rule: ${{ github.event.inputs.bump }}"
              exit 1
              ;;
          esac
          
          case ${{ github.event.inputs.release }} in 
            local)
              ;;
            global)
              ;;
            *)
              echo invalid release type: ${{ github.event.inputs.release }}
              exit 1
              ;;
          esac
          
          echo BUMP=${{ github.event.inputs.bump }} >> $GITHUB_ENV
          echo RELEASE=${{ github.event.inputs.release }} >> $GITHUB_ENV
          echo VERSION=${{ github.event.inputs.version }} >> $GITHUB_ENV
          echo GRPC_VERSION=${{ github.event.inputs.grpc_version }} >> $GITHUB_ENV
              
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.7
          
      - name: Setup poetry
        uses: abatilo/actions-poetry@v2.1.0
        
      - name: Bump grpc
        if: github.event.inputs.grpc_version == '' && env.RELEASE == 'local'
        run: |
          GRPC_VERSION=$(curl -Ls https://pypi.org/pypi/hydro-serving-grpc/json | jq -r '.releases | keys[-1]')
          echo $GRPC_VERSION
         # poetry add hydro-serving-grpc=$GRPC_VERSION
          
      - name: Bump grpc to latest stable version
        if: env.GRPC_VERSION == '' && env.RELEASE == 'global'
        run: |
          GRPC_VERSION=$(curl -Ls https://pypi.org/pypi/hydro-serving-grpc/json | jq -r .info.version)
          echo $GRPC_VERSION
          poetry add hydro-serving-grpc=$GRPC_VERSION
          
      - name: Set manual grpc version
        if: env.GRPC_VERSION != ''
        run: poetry add hydro-serving-grpc=${{ env.GRPC_VERSION }}
          
      - name: Install dependencies
        run: poetry install
        
      - name: bump version
        if: env.VERSION == ''
        run: poetry version ${{ env.BUMP }}
        
      - name: force bump version
        if: github.events.inputs.version != ''
        run: poetry version ${{ env.VERSION }}
        
      - name: Build
        run: poetry build
          
      - name: Publish
        run: |
          poetry publish -u __token__ -p ${{ secrets.pypi_token }}
          
      - name: Tag and push changes
        id: tag
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -a --allow-empty -m "release version $(poetry version -s)"
          git tag $(poetry version -s)
          git push
          git push --tags

      - name: Reports
        id: generate-output
        run: echo "::set-output name=tag-output::$(poetry version -s)"

    outputs:
      tag: ${{ steps.generate-output.outputs.tag-output }}
          
  slackNotification:
    name: Slack Notification
    needs: Release
    runs-on: ubuntu-latest
    steps:
    - name: Slack Notification success
      if: ${{ success() }}
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_CHANNEL: hydrosphere
        SLACK_USERNAME: HydroRobot
        SLACK_ICON: https://avatars.githubusercontent.com/u/17550625?s=200&v=4
        SLACK_COLOR: ${{ job.status }}
        SLACK_TITLE: Build status - success
        SLACK_MESSAGE: "Releasing hydrosdk ${{ needs.Release.outputs.tag }} :rocket:"
        MSG_MINIMAL: true

    - name: Slack Notification failure
      if: ${{ failure() }}
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_CHANNEL: hydrosphere
        SLACK_USERNAME: HydroRobot
        SLACK_ICON: https://avatars.githubusercontent.com/u/17550625?s=200&v=4
        SLACK_COLOR: ${{ job.status }}
        SLACK_TITLE: Build status - failure
        SLACK_MESSAGE: "Check build $GITHUB_RUN_ID status"
        MSG_MINIMAL: true